//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShopSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoffeeShopSystemDBEntities : DbContext
    {
        public CoffeeShopSystemDBEntities()
            : base("name=CoffeeShopSystemDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Commande> CommandeSet { get; set; }
        public virtual DbSet<Cafe> CafeSet { get; set; }
        public virtual DbSet<Caissier> CaissierSet { get; set; }
        public virtual DbSet<Barista> BaristaSet { get; set; }
        public virtual DbSet<Option> OptionSet { get; set; }
        public virtual DbSet<Type> TypeSet { get; set; }
        public virtual DbSet<Ingredient> IngredientSet { get; set; }
        public virtual DbSet<Taille> TailleSet { get; set; }
        public virtual DbSet<HistoriqueSet> HistoriqueSet { get; set; }
    }
}
