//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShopSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commande()
        {
            this.Cafe = new HashSet<Cafe>();
            this.HistoriqueSet = new HashSet<HistoriqueSet>();
        }
    
        public int Id { get; set; }
        public string nomClient { get; set; }
        public System.DateTime date { get; set; }
        public string commentaire { get; set; }
        public string statut { get; set; }
        public Nullable<int> duree { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cafe> Cafe { get; set; }
        public virtual Barista Barista { get; set; }
        public virtual Caissier Caissier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoriqueSet> HistoriqueSet { get; set; }
    }
}
